"""cascade delete

Revision ID: fea3c4bb71c3
Revises: c29ed6b7f212
Create Date: 2021-02-04 13:11:20.096068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea3c4bb71c3'
down_revision = 'c29ed6b7f212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_postId_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['postId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('likes_postId_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'posts', ['postId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_postId_fkey', 'likes', 'posts', ['postId'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_postId_fkey', 'comments', 'posts', ['postId'], ['id'])
    # ### end Alembic commands ###
